### ISSUE TITLE
Tutorial reference card location?

### ISSUE THREAD

**Issue by cacology** [scholarslab/clockwork#53] opened 2016-05-02 11:36 UTC
Where should it be? Right now, it's just on the back-end: https://github.com/scholarslab/clockwork/tree/gh-pages/reference-card

**Comment by racheldevorah** [comment] 2016-05-02 16:01
yes! does it warrant its own accordion fold in the curriculum?

**Comment by cacology** [comment] 2016-05-02 18:01
Makes sense to me- perhaps see what the Curriculum folks say? I'm not 100% about the mode and genre of that document, so if it would fit.

**Comment by erochest** [comment] 2016-05-03 14:20
Duplicate of #35

**Closed as completed by erochest** 2016-05-03 14:20 UTC
