### ISSUE TITLE
Sonifications look broken on cell phone screen

### ISSUE THREAD

**Issue by reedeth** [scholarslab/clockwork#39] opened 2016-04-30 14:03 UTC
When I look at the Sonification page on my cellphone, the videos look strange and out of place and not aligned with the rest of the site. When I click on them they take up the whole screen and are fine, but as it stands right now they look pretty wonky before you click.

**Comment by erochest** [comment] 2016-05-03 14:06
Duplicate of #20.

**Closed as completed by erochest** 2016-05-03 14:06 UTC
